# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cf8bae3546f5c4b2e4f505402ce4625f2c66abf9f8c0159764867272742b15a908905e3afb1009b236538ac42d9a96da0d5ea5a870fd4b381f4665c9a4e0a65

test:
  secret_key_base: 23433c74283a35fea83b94bb69deca29767538d17d270eaabfac2fb7e926b8eadac48967c2fc6c87f6e6612186c419fb8eee869ef9db841cbffe42ff11da1f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
